//
//  TimelineEditorView.swift
//  AudioSplitter
//
//  Created by Aryan Rogye on 2/12/26.
//

import SwiftUI

extension TimelineEditorView {
    
    @Observable
    class TimelineClip: Identifiable {
        let id = UUID()
        let asset: StoredStemAsset
        var startTime: TimeInterval = 0.0 // This is the delay in seconds
        
        nonisolated init(asset: StoredStemAsset) {
            self.asset = asset
        }
    }
    
    @Observable
    @MainActor
    class TimelineSong {
        /// NO map because we may want multiple of the same URLs
        var clips: [TimelineClip] = []
        var audios: [AVAudioPreviewPlayback] = []
        
        private var startTime: Date?
        private var accumulatedTime: TimeInterval = 0

        var isRunning: Bool {
            return startTime != nil
        }
        
        public func play() throws {
            if accumulatedTime > 0 {
                for audio in audios {
                    Task {
                        audio.play()
                    }
                }
            } else {
                /// once added we play all at the same time
                for i in 0..<audios.count {
                    let audio = audios[i]
                    
                    if i < clips.count {
                        let clip = clips[i]
                        
                        /// TODO: Generated by Gemini, Look this over
                        Task {
                            // 1. Calculate the delay based on accumulated time
                            // If we are resuming, we need to account for where we paused
                            let delay = max(0, clip.startTime - accumulatedTime)
                            
                            if delay > 0 {
                                // Wait before playing
                                try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
                            }
                            
                            // 2. Play
                            // Note: If we are resuming past the delay, we might need to seek.
                            // For MVP, simple play is fine.
                            try self.playAudio(previewAudio: audio, url: clip.asset.fileURL, time: 0)
                        }
                    }
                }
            }
        }

        public func pause() throws {
            for audio in audios {
                Task {
                    audio.pause()
                }
            }
            
            if let startTime = startTime {
                // Calculate the duration since the timer started and add it to accumulated time
                accumulatedTime += Date().timeIntervalSince(startTime)
                self.startTime = nil
            }
        }
        
        private func playAudio(previewAudio: AVAudioPreviewPlayback, url: URL, time: TimeInterval) throws {
            try previewAudio.togglePreview(fileURL: url, startTime: time)
            startTime = Date()
            print("Played Song")
        }
        

        public func assign(_ items: [ProcessedTrackHistoryItem]) {
            Task.detached(priority: .userInitiated) {
                var stems: [TimelineClip] = []
                
                /// Each stem has a file url which gets added into `addedURLs`
                /// when we call play this will bundle up all and toggle play on them
                for item in items {
                    for stem in item.stems {
                        let clip = TimelineClip(asset: stem)
                        stems.append(clip)
                    }
                }
                
                await MainActor.run { [stems] in
                    self.clips.append(contentsOf: stems)
                    self.seedAudio()
                }
            }
        }
        
        public func remove(_ clip: TimelineClip) {
            clips.removeAll { $0.id == clip.id }
            seedAudio()
        }
        
        /// Function Seeds after audio is changed based on addedURLs
        private func seedAudio() {
            audios.removeAll()
            startTime = nil
            accumulatedTime = .zero
            for _ in clips {
                let previewAudio = AVAudioPreviewPlayback()
                audios.append(previewAudio)
            }
        }
    }
    
    @Observable
    @MainActor
    internal final class TimelineViewModel {
        var timelineSong = TimelineSong()
        var playbackError: String?
        var shouldShowError = false
        
        var isPlaying : Bool {
            timelineSong.isRunning
        }

        public func addDroppedItems(_ items: [ProcessedTrackHistoryItem]) {
            timelineSong.assign(items)
        }
        
        public func removeURLFromSong(_ clip: TimelineClip) {
            timelineSong.remove(clip)
        }
        
        public func toggleAudio() {
            do {
                if isPlaying {
                    try timelineSong.pause()
                } else {
                    try timelineSong.play()
                }
            } catch let error as StagePreviewPlaybackError {
                switch error {
                case .missingTrack(let role):
                    playbackError = "Missing Track: \(role)"
                case .fileMissing(let path):
                    playbackError = "File Missing: \(path)"
                case .failedToStart:
                    playbackError = "Failed To Start"
                case .playbackFailed(let details):
                    playbackError = "Playback Failed: \(details)"
                }
                shouldShowError = true
            } catch {
                playbackError = error.localizedDescription
                shouldShowError = true
            }
        }
    }
}

struct TimelineEditorView: View {
    
    @State private var vm = TimelineViewModel()
    
    let shape = UnevenRoundedRectangle(
        topLeadingRadius: 0,
        bottomLeadingRadius: 32,
        bottomTrailingRadius: 32,
        topTrailingRadius: 0,
        style: .continuous
    )
    
    let pixelsPerSecond: CGFloat = 20
    
    /**
     
     For Each AudioTrack Gets Added In:
     [      song name     ]
     [     song vocal     ]
     [ song instrumentals ]
     
     */
    
    var body: some View {
        VStack(spacing: 0) {
            /// Controls For Playback, Right now only PlayPasue Button here
            HStack {
                Spacer()
                Button {
                    vm.toggleAudio()
                } label: {
                    Image(systemName: vm.isPlaying ?  "stop.fill" : "play.fill")
                }
                Spacer()
            }
            .buttonStyle(PlayButtonStyle())
            .padding(.vertical, 6)
            
            Divider()
            
            timelineContent
            
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color(.systemGray6))
        .dropDestination(for: ProcessedTrackHistoryItem.self) { items, location in
            withAnimation(.spring()) {
                vm.addDroppedItems(items)
            }
            return true
        }
    }
    
    private var emptyStateView: some View {
        VStack {
            Image(systemName: "square.and.arrow.down")
                .font(.largeTitle)
            Text("Drop stems here")
                .font(.headline)
        }
        .foregroundStyle(.secondary)
        .frame(maxWidth: .infinity, minHeight: 200)
    }
    
    private var timelineContent: some View {
        Text("Somethjing")
    }
    
//    private var timelineContent: some View {
//        ScrollView([.vertical, .horizontal], showsIndicators: false) {
//            VStack(alignment: .leading, spacing: 12) {
//                if vm.timelineSong.clips.isEmpty {
//                    emptyStateView
//                } else {
//                    ForEach(vm.timelineSong.clips) { clip in
//                        TimelineTrackLane(
//                            clip: clip,
//                            pixelsPerSecond: pixelsPerSecond
//                        )
//                        .contextMenu {
//                            Button(role: .destructive) {
//                                vm.removeURLFromSong(clip)
//                            } label: {
//                                Label("Remove Stem", systemImage: "trash")
//                            }
//                        }
//                    }
//                }
//            }
//            .padding(.vertical, 20)
//        }
//    }
}

extension TimelineEditorView {
    
    struct TimelineTrackLane: View {
        // 1. Use @Bindable so we can write to it directly
        @Bindable var clip: TimelineClip
        let pixelsPerSecond: CGFloat
        
        // 2. We store the "Original" time when you start dragging
        @State private var initialStartTime: TimeInterval? = nil
        
        let mockDuration: TimeInterval = 30
        
        var body: some View {
            HStack(spacing: 0) {
                
                // --- HEADER (Same as before) ---
                VStack(alignment: .trailing, spacing: 4) {
                    Text(clip.asset.displayName)
                        .font(.system(size: 11, weight: .bold, design: .rounded))
                        .lineLimit(1)
                    
                    Text(clip.asset.kind.rawValue.capitalized)
                        .font(.system(size: 9, weight: .semibold))
                        .foregroundStyle(clip.asset.kind == .vocals ? .blue : .green)
                        .padding(.horizontal, 4)
                        .padding(.vertical, 2)
                        .background(
                            (clip.asset.kind == .vocals ? Color.blue : Color.green).opacity(0.1),
                            in: Capsule()
                        )
                }
                .frame(width: 80, alignment: .trailing)
                .padding(.trailing, 10)
                
                // --- TIMELINE LANE ---
                ZStack(alignment: .leading) {
                    // Lane Background
                    RoundedRectangle(cornerRadius: 6)
                        .fill(Color.black.opacity(0.03))
                        .frame(height: 50)
                        .frame(maxWidth: .infinity)
                    
                    // The Clip
                    RoundedRectangle(cornerRadius: 4)
                        .fill(clip.asset.kind == .vocals ? Color.blue.opacity(0.8) : Color.green.opacity(0.8))
                        .frame(width: mockDuration * pixelsPerSecond, height: 40)
                        .overlay(alignment: .leading) {
                            HStack(spacing: 4) {
                                Image(systemName: clip.asset.kind == .vocals ? "mic.fill" : "hifispeaker.fill")
                                    .font(.caption2)
                                Text(clip.asset.kind.rawValue.capitalized)
                                    .font(.caption2.bold())
                                
                                // Show live time update
                                if clip.startTime > 0 {
                                    Text("+\(clip.startTime, specifier: "%.1f")s")
                                        .font(.caption2)
                                        .opacity(0.8)
                                        .monospacedDigit()
                                }
                            }
                            .foregroundStyle(.white.opacity(0.9))
                            .padding(.leading, 8)
                        }
                        .shadow(color: .black.opacity(0.15), radius: 3, x: 0, y: 2)
                    
                    // MARK: - LIVE DRAG LOGIC
                    // We use the actual model time for the offset. No separate "dragOffset" variable.
                        .offset(x: clip.startTime * pixelsPerSecond)
                        .gesture(
                            DragGesture()
                                .onChanged { value in
                                    // 1. Snapshot the start time if this is the first frame of the drag
                                    if initialStartTime == nil {
                                        initialStartTime = clip.startTime
                                    }
                                    
                                    guard let start = initialStartTime else { return }
                                    
                                    // 2. Calculate the delta in seconds
                                    let timeDelta = value.translation.width / pixelsPerSecond
                                    
                                    // 3. Update the model LIVE (Preventing negative time)
                                    clip.startTime = max(0, start + timeDelta)
                                }
                                .onEnded { _ in
                                    // 4. Clear the snapshot so the next drag starts fresh
                                    initialStartTime = nil
                                }
                        )
                }
                .clipped()
            }
            .padding(.horizontal, 8)
            .frame(height: 60)
        }
    }
}
